#!/usr/bin/env bash
# Generates src/handlers/letgo_native_names.rs — the list of let-go core
# functions implemented natively in Go (runtime type NativeFn): the
# clojure.core names let-go provides WITHOUT a `.lg` definition, so they have no
# source to navigate into. Used for hover/completion only.
#
# DEV-ONLY / OFFLINE. clj-pulse never runs this (or `lg`) at runtime — the
# committed output is a plain static table, used only as a FALLBACK: at runtime
# the server prefers names harvested live from the pinned version's
# `pkg/rt/lang.go` (see `lgx::parse_native_defs`), so this list only matters when
# the let-go source isn't on disk (unpinned project, non-lgx install). Re-run
# when bumping the supported let-go version:
#
#     bb gen-letgo-natives        # requires the `lg` binary on PATH
#
# Method (no Go parsing): take the clojure.core names already in
# src/index/core.rs, ask the installed let-go runtime the type of each via
# (type (resolve (symbol name))), and keep the ones that are NativeFn. `.lg`-
# defined fns (type Fn, e.g. map/when) and names absent from this build (nil)
# are dropped — they are served by the live `.lg` index instead.
set -euo pipefail

cd "$(dirname "$0")/.."

CORE_RS="src/index/core.rs"
OUT="src/handlers/letgo_native_names.rs"

command -v lg >/dev/null || { echo "error: 'lg' not found on PATH" >&2; exit 1; }

# clojure.core candidate names from the existing static table (anchored on the
# struct literal so docstrings can't false-match).
names="$(grep -oE 'CoreSymbol \{ name: "([^"]+)"' "$CORE_RS" \
  | sed -E 's/^CoreSymbol \{ name: "//; s/"$//' | LC_ALL=C sort -u)"

# Build a probe script: print "name<TAB>type" for each candidate. Names are fed
# as strings (so reader edge cases like +, *', .. are harmless); each lookup is
# guarded so one bad name can't abort the run. `mktemp -d` is portable across
# GNU and BSD/macOS, unlike `mktemp --suffix`.
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT
probe="$tmpdir/probe.lg"
{
  printf '(doseq [s ['
  while IFS= read -r n; do
    esc="${n//\\/\\\\}"; esc="${esc//\"/\\\"}"
    printf '"%s" ' "$esc"
  done <<< "$names"
  printf ']]\n'
  printf '  (println (str s "\\t" (try (type (resolve (symbol s))) (catch e "ERR")))))\n'
} > "$probe"

# Keep names whose runtime type is NativeFn; bytewise sort to match Rust str Ord
# (required for binary_search).
natives="$(lg "$probe" | awk -F'\t' '$2 ~ /NativeFn/ {print $1}' | LC_ALL=C sort -u)"

count="$(printf '%s\n' "$natives" | grep -c . || true)"
[ "$count" -gt 0 ] || { echo "error: no natives found (is lg working?)" >&2; exit 1; }

{
  echo "// GENERATED by scripts/gen_letgo_native_names.sh — do not edit by hand."
  echo "// Refresh after bumping the supported let-go version: bb gen-letgo-natives"
  echo "//"
  echo "// FALLBACK only: at runtime the server prefers names harvested live from the"
  echo "// pinned version's pkg/rt/lang.go (lgx::parse_native_defs); this static list is"
  echo "// used when the let-go source isn't on disk (unpinned project / non-lgx install)."
  echo "//"
  echo "// let-go core functions implemented natively in Go (runtime type NativeFn):"
  echo "// the clojure.core names let-go provides without a \`.lg\` definition, so they"
  echo "// have no source to navigate to. Used for hover/completion only; docs are"
  echo "// borrowed from the clojure.core table (core.rs). Sorted for binary_search."
  echo "pub static NATIVE_NAMES: &[&str] = &["
  while IFS= read -r n; do
    [ -n "$n" ] || continue
    esc="${n//\\/\\\\}"; esc="${esc//\"/\\\"}"
    printf '    "%s",\n' "$esc"
  done <<< "$natives"
  echo "];"
} > "$OUT"

echo "wrote $OUT ($count native names)"
