#!/usr/bin/env bash
# Generate the Homebrew formula for clj-pulse from a release checksums.txt.
#
# Usage:
#   scripts/generate-formula.sh VERSION CHECKSUMS_FILE > clj-pulse.rb
#
# Args:
#   VERSION         release version without the v prefix (e.g. 0.0.1-alpha-3)
#   CHECKSUMS_FILE  path to the release checksums.txt (sha256sum format)
#
# Release CI runs this to update Formula/clj-pulse.rb in
# https://github.com/abogoyavlensky/homebrew-tap on every release.

set -euo pipefail

err() { printf 'error: %s\n' "$*" >&2; exit 1; }

[ $# -eq 2 ] || err "usage: $0 VERSION CHECKSUMS_FILE"

version="$1"
checksums="$2"

[ -f "$checksums" ] || err "checksums file not found: $checksums"

# Look up the sha256 for a release artifact by Rust target triple. clj-pulse
# archives embed the triple (not the version) in the filename, and the version
# lives only in the download URL path.
sha_for() {
  local target="$1" sha
  sha=$(awk -v f="clj-pulse-${target}.tar.gz" '$2 == f { print $1 }' "$checksums")
  [ -n "$sha" ] || err "no checksum for clj-pulse-${target}.tar.gz in ${checksums}"
  printf '%s' "$sha"
}

darwin_arm64=$(sha_for aarch64-apple-darwin)
darwin_amd64=$(sha_for x86_64-apple-darwin)
linux_amd64=$(sha_for x86_64-unknown-linux-gnu)
linux_arm64=$(sha_for aarch64-unknown-linux-gnu)

cat <<EOF
# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/clj-pulse. DO NOT EDIT.
class CljPulse < Formula
  desc "Language server for Clojure"
  homepage "https://github.com/abogoyavlensky/clj-pulse"
  version "${version}"
  license "MIT"

  livecheck do
    skip "Formula is updated by clj-pulse release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v${version}/clj-pulse-x86_64-apple-darwin.tar.gz"
      sha256 "${darwin_amd64}"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v${version}/clj-pulse-aarch64-apple-darwin.tar.gz"
      sha256 "${darwin_arm64}"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v${version}/clj-pulse-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_amd64}"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v${version}/clj-pulse-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_arm64}"
    end
  end

  def install
    bin.install "clj-pulse"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clj-pulse --version")
  end
end
EOF
